# Generated by Django 3.2.13 on 2022-07-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0002_alter_reply_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
